// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/analysis.dart';
import 'api/filters.dart';
import 'api/image.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 109111124;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'silvestre_flutter_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<SilvestreImageWrapper> crateApiFiltersApplyFilter({
    required SilvestreImageWrapper img,
    required String name,
    required String paramsJson,
  });

  Future<HistogramResult> crateApiAnalysisComputeHistogram({
    required SilvestreImageWrapper img,
  });

  Future<HistogramResult?> crateApiAnalysisComputeLuminanceHistogram({
    required SilvestreImageWrapper img,
  });

  Future<SilvestreImageWrapper> crateApiImageCreateImage({
    required List<int> pixels,
    required int width,
    required int height,
    required String colorSpace,
  });

  Future<Uint8List> crateApiImageEncodeImage({
    required SilvestreImageWrapper img,
    required String format,
  });

  Future<String> crateApiImageImageColorSpace({
    required SilvestreImageWrapper img,
  });

  Future<int> crateApiImageImageHeight({required SilvestreImageWrapper img});

  Future<Uint8List> crateApiImageImagePixels({
    required SilvestreImageWrapper img,
  });

  Future<int> crateApiImageImageWidth({required SilvestreImageWrapper img});

  Future<SilvestreImageWrapper> crateApiImageLoadImageFromBytes({
    required List<int> bytes,
  });

  Future<SilvestreImageWrapper> crateApiImageLoadImageFromPath({
    required String path,
  });

  Future<void> crateApiImageSaveImage({
    required SilvestreImageWrapper img,
    required String path,
    required String format,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SilvestreImageWrapper;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SilvestreImageWrapper;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SilvestreImageWrapperPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<SilvestreImageWrapper> crateApiFiltersApplyFilter({
    required SilvestreImageWrapper img,
    required String name,
    required String paramsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
            img,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_String(paramsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFiltersApplyFilterConstMeta,
        argValues: [img, name, paramsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFiltersApplyFilterConstMeta => const TaskConstMeta(
    debugName: "apply_filter",
    argNames: ["img", "name", "paramsJson"],
  );

  @override
  Future<HistogramResult> crateApiAnalysisComputeHistogram({
    required SilvestreImageWrapper img,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
            img,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_histogram_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisComputeHistogramConstMeta,
        argValues: [img],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisComputeHistogramConstMeta =>
      const TaskConstMeta(debugName: "compute_histogram", argNames: ["img"]);

  @override
  Future<HistogramResult?> crateApiAnalysisComputeLuminanceHistogram({
    required SilvestreImageWrapper img,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
            img,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_histogram_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisComputeLuminanceHistogramConstMeta,
        argValues: [img],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisComputeLuminanceHistogramConstMeta =>
      const TaskConstMeta(
        debugName: "compute_luminance_histogram",
        argNames: ["img"],
      );

  @override
  Future<SilvestreImageWrapper> crateApiImageCreateImage({
    required List<int> pixels,
    required int width,
    required int height,
    required String colorSpace,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pixels, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_String(colorSpace, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCreateImageConstMeta,
        argValues: [pixels, width, height, colorSpace],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCreateImageConstMeta => const TaskConstMeta(
    debugName: "create_image",
    argNames: ["pixels", "width", "height", "colorSpace"],
  );

  @override
  Future<Uint8List> crateApiImageEncodeImage({
    required SilvestreImageWrapper img,
    required String format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
            img,
            serializer,
          );
          sse_encode_String(format, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageEncodeImageConstMeta,
        argValues: [img, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageEncodeImageConstMeta => const TaskConstMeta(
    debugName: "encode_image",
    argNames: ["img", "format"],
  );

  @override
  Future<String> crateApiImageImageColorSpace({
    required SilvestreImageWrapper img,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
            img,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiImageImageColorSpaceConstMeta,
        argValues: [img],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageImageColorSpaceConstMeta =>
      const TaskConstMeta(debugName: "image_color_space", argNames: ["img"]);

  @override
  Future<int> crateApiImageImageHeight({required SilvestreImageWrapper img}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
            img,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiImageImageHeightConstMeta,
        argValues: [img],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageImageHeightConstMeta =>
      const TaskConstMeta(debugName: "image_height", argNames: ["img"]);

  @override
  Future<Uint8List> crateApiImageImagePixels({
    required SilvestreImageWrapper img,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
            img,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiImageImagePixelsConstMeta,
        argValues: [img],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageImagePixelsConstMeta =>
      const TaskConstMeta(debugName: "image_pixels", argNames: ["img"]);

  @override
  Future<int> crateApiImageImageWidth({required SilvestreImageWrapper img}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
            img,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiImageImageWidthConstMeta,
        argValues: [img],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageImageWidthConstMeta =>
      const TaskConstMeta(debugName: "image_width", argNames: ["img"]);

  @override
  Future<SilvestreImageWrapper> crateApiImageLoadImageFromBytes({
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageLoadImageFromBytesConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageLoadImageFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "load_image_from_bytes",
        argNames: ["bytes"],
      );

  @override
  Future<SilvestreImageWrapper> crateApiImageLoadImageFromPath({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageLoadImageFromPathConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageLoadImageFromPathConstMeta =>
      const TaskConstMeta(
        debugName: "load_image_from_path",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiImageSaveImage({
    required SilvestreImageWrapper img,
    required String path,
    required String format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
            img,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_String(format, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageSaveImageConstMeta,
        argValues: [img, path, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageSaveImageConstMeta => const TaskConstMeta(
    debugName: "save_image",
    argNames: ["img", "path", "format"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SilvestreImageWrapper =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SilvestreImageWrapper =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper;

  @protected
  SilvestreImageWrapper
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SilvestreImageWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SilvestreImageWrapper
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SilvestreImageWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SilvestreImageWrapper
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SilvestreImageWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  HistogramResult dco_decode_box_autoadd_histogram_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_histogram_result(raw);
  }

  @protected
  ChannelStatsResult dco_decode_channel_stats_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ChannelStatsResult(
      min: dco_decode_u_8(arr[0]),
      max: dco_decode_u_8(arr[1]),
      mean: dco_decode_f_64(arr[2]),
      stdDev: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HistogramResult dco_decode_histogram_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HistogramResult(
      bins: dco_decode_list_list_prim_u_64_strict(arr[0]),
      stats: dco_decode_list_channel_stats_result(arr[1]),
      pixelCount: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  List<ChannelStatsResult> dco_decode_list_channel_stats_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_channel_stats_result).toList();
  }

  @protected
  List<Uint64List> dco_decode_list_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_u_64_strict)
        .toList();
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  HistogramResult? dco_decode_opt_box_autoadd_histogram_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_histogram_result(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  SilvestreImageWrapper
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SilvestreImageWrapperImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SilvestreImageWrapper
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SilvestreImageWrapperImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SilvestreImageWrapper
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SilvestreImageWrapperImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  HistogramResult sse_decode_box_autoadd_histogram_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_histogram_result(deserializer));
  }

  @protected
  ChannelStatsResult sse_decode_channel_stats_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_min = sse_decode_u_8(deserializer);
    var var_max = sse_decode_u_8(deserializer);
    var var_mean = sse_decode_f_64(deserializer);
    var var_stdDev = sse_decode_f_64(deserializer);
    return ChannelStatsResult(
      min: var_min,
      max: var_max,
      mean: var_mean,
      stdDev: var_stdDev,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HistogramResult sse_decode_histogram_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bins = sse_decode_list_list_prim_u_64_strict(deserializer);
    var var_stats = sse_decode_list_channel_stats_result(deserializer);
    var var_pixelCount = sse_decode_u_64(deserializer);
    return HistogramResult(
      bins: var_bins,
      stats: var_stats,
      pixelCount: var_pixelCount,
    );
  }

  @protected
  List<ChannelStatsResult> sse_decode_list_channel_stats_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChannelStatsResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_channel_stats_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint64List> sse_decode_list_list_prim_u_64_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint64List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_64_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  HistogramResult? sse_decode_opt_box_autoadd_histogram_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_histogram_result(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
    SilvestreImageWrapper self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SilvestreImageWrapperImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
    SilvestreImageWrapper self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SilvestreImageWrapperImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSilvestreImageWrapper(
    SilvestreImageWrapper self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SilvestreImageWrapperImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_histogram_result(
    HistogramResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_histogram_result(self, serializer);
  }

  @protected
  void sse_encode_channel_stats_result(
    ChannelStatsResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.min, serializer);
    sse_encode_u_8(self.max, serializer);
    sse_encode_f_64(self.mean, serializer);
    sse_encode_f_64(self.stdDev, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_histogram_result(
    HistogramResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_list_prim_u_64_strict(self.bins, serializer);
    sse_encode_list_channel_stats_result(self.stats, serializer);
    sse_encode_u_64(self.pixelCount, serializer);
  }

  @protected
  void sse_encode_list_channel_stats_result(
    List<ChannelStatsResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_channel_stats_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_64_strict(
    List<Uint64List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_64_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_histogram_result(
    HistogramResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_histogram_result(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class SilvestreImageWrapperImpl extends RustOpaque
    implements SilvestreImageWrapper {
  // Not to be used by end users
  SilvestreImageWrapperImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SilvestreImageWrapperImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib
            .instance
            .api
            .rust_arc_increment_strong_count_SilvestreImageWrapper,
    rustArcDecrementStrongCount:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_SilvestreImageWrapper,
    rustArcDecrementStrongCountPtr:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_SilvestreImageWrapperPtr,
  );
}
