#ifndef SILVESTRE_H
#define SILVESTRE_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Return the version string of the silvestre library.
 *
 * # Safety
 * The returned pointer is valid for the lifetime of the program.
 */
const char *silvestre_version(void);

#endif  /* SILVESTRE_H */
