name: silvestre_flutter
description: Flutter plugin for silvestre image processing library, powered by flutter_rust_bridge.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.12.0
  meta: ^1.11.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
