// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `histogram_to_result`

/// Compute a per-channel histogram for the image.
Future<HistogramResult> computeHistogram({
  required SilvestreImageWrapper img,
}) => RustLib.instance.api.crateApiAnalysisComputeHistogram(img: img);

/// Compute a single-channel luminance histogram (BT.601 weights).
///
/// Returns `None` for unsupported color spaces (currently all are supported).
Future<HistogramResult?> computeLuminanceHistogram({
  required SilvestreImageWrapper img,
}) => RustLib.instance.api.crateApiAnalysisComputeLuminanceHistogram(img: img);

/// Per-channel statistics returned from histogram computation.
class ChannelStatsResult {
  final int min;
  final int max;
  final double mean;
  final double stdDev;

  const ChannelStatsResult({
    required this.min,
    required this.max,
    required this.mean,
    required this.stdDev,
  });

  @override
  int get hashCode =>
      min.hashCode ^ max.hashCode ^ mean.hashCode ^ stdDev.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelStatsResult &&
          runtimeType == other.runtimeType &&
          min == other.min &&
          max == other.max &&
          mean == other.mean &&
          stdDev == other.stdDev;
}

/// Result of a histogram computation.
///
/// `bins` is a `Vec<Vec<u64>>` where `bins[channel]` has 256 entries,
/// one count per possible intensity value (0–255).
class HistogramResult {
  final List<Uint64List> bins;
  final List<ChannelStatsResult> stats;
  final BigInt pixelCount;

  const HistogramResult({
    required this.bins,
    required this.stats,
    required this.pixelCount,
  });

  @override
  int get hashCode => bins.hashCode ^ stats.hashCode ^ pixelCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistogramResult &&
          runtimeType == other.runtimeType &&
          bins == other.bins &&
          stats == other.stats &&
          pixelCount == other.pixelCount;
}
