// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'image.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_named_filter`, `get_f32`, `get_f64`, `get_i32`, `get_str`, `get_u32`, `get_usize`

/// Apply a named filter to an image, returning a new image.
///
/// # Parameters
///
/// - `name`: one of `grayscale`, `invert`, `sepia`, `brightness`, `contrast`,
///   `sharpen`, `box_blur`, `sobel`, `gaussian`, `median`, `canny`,
///   `crop`, `resize`, `rotate`, `mirror`.
/// - `params_json`: a JSON object with filter-specific parameters.
///   Pass `"{}"` or `""` for filters that take no parameters.
///
/// ## Parameter table
///
/// | Filter       | JSON params                                        |
/// |--------------|----------------------------------------------------|
/// | `grayscale`  | *(none)*                                           |
/// | `invert`     | *(none)*                                           |
/// | `sepia`      | *(none)*                                           |
/// | `sharpen`    | *(none)*                                           |
/// | `box_blur`   | *(none)*                                           |
/// | `sobel`      | *(none)*                                           |
/// | `brightness` | `{"delta": <i32>}`                                 |
/// | `contrast`   | `{"factor": <f32>}`                                |
/// | `gaussian`   | `{"sigma": <f32>}`                                 |
/// | `median`     | `{"size": <usize>}`                                |
/// | `canny`      | `{"low": <f32>, "high": <f32>, "sigma": <f32>}`   |
/// | `crop`       | `{"x": <u32>, "y": <u32>, "w": <u32>, "h": <u32>}`|
/// | `resize`     | `{"w": <u32>, "h": <u32>}`                         |
/// | `rotate`     | `{"angle": <f64>}`                                 |
/// | `mirror`     | `{"mode": "horizontal"\|"vertical"\|"both"}`       |
Future<SilvestreImageWrapper> applyFilter({
  required SilvestreImageWrapper img,
  required String name,
  required String paramsJson,
}) => RustLib.instance.api.crateApiFiltersApplyFilter(
  img: img,
  name: name,
  paramsJson: paramsJson,
);
