// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_color_space`, `parse_format`

/// Load an image from a file path (PNG, JPEG, BMP).
Future<SilvestreImageWrapper> loadImageFromPath({required String path}) =>
    RustLib.instance.api.crateApiImageLoadImageFromPath(path: path);

/// Load an image from raw encoded bytes (PNG, JPEG, BMP).
Future<SilvestreImageWrapper> loadImageFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageLoadImageFromBytes(bytes: bytes);

/// Create an image from raw pixel data.
///
/// `color_space` must be one of: `"rgba"`, `"rgb"`, `"grayscale"`.
Future<SilvestreImageWrapper> createImage({
  required List<int> pixels,
  required int width,
  required int height,
  required String colorSpace,
}) => RustLib.instance.api.crateApiImageCreateImage(
  pixels: pixels,
  width: width,
  height: height,
  colorSpace: colorSpace,
);

/// Get the image width in pixels.
Future<int> imageWidth({required SilvestreImageWrapper img}) =>
    RustLib.instance.api.crateApiImageImageWidth(img: img);

/// Get the image height in pixels.
Future<int> imageHeight({required SilvestreImageWrapper img}) =>
    RustLib.instance.api.crateApiImageImageHeight(img: img);

/// Get the image color space as a string (`"rgba"`, `"rgb"`, or `"grayscale"`).
Future<String> imageColorSpace({required SilvestreImageWrapper img}) =>
    RustLib.instance.api.crateApiImageImageColorSpace(img: img);

/// Get a copy of the raw pixel data.
Future<Uint8List> imagePixels({required SilvestreImageWrapper img}) =>
    RustLib.instance.api.crateApiImageImagePixels(img: img);

/// Save the image to a file path in the specified format.
///
/// `format` must be one of: `"png"`, `"jpeg"` / `"jpg"`, `"bmp"`.
Future<void> saveImage({
  required SilvestreImageWrapper img,
  required String path,
  required String format,
}) => RustLib.instance.api.crateApiImageSaveImage(
  img: img,
  path: path,
  format: format,
);

/// Encode the image to in-memory bytes in the specified format.
///
/// `format` must be one of: `"png"`, `"jpeg"` / `"jpg"`, `"bmp"`.
Future<Uint8List> encodeImage({
  required SilvestreImageWrapper img,
  required String format,
}) => RustLib.instance.api.crateApiImageEncodeImage(img: img, format: format);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SilvestreImageWrapper>>
abstract class SilvestreImageWrapper implements RustOpaqueInterface {}
